main: com.doxa.ninja.Main
name: Ninja
version: 1.4
description: Ninja by Nick Doxa.
api-version: 1.16
author: Nick Doxa
depend: [WorldGuard]
commands:
  ninja:
    description: main command for ninja core!
  n:
    description: alias for the main ninja command!